### ISSUE TITLE
IP Checks for release v2.1.0: Internacionalization vue-i18n

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#160]
## IP Check Resume:

There was an IP check opened for the `vue-i18n` library which is responsible for the internationalization mechanism in the digital product pass application.

Because of that this functionality got postponed for the release `v2.1.0`

## Open Issues

- [ ] [npm/npmjs/@intlify/core-base/9.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12452) 
- [ ] [npm/npmjs/@intlify/message-compiler/9.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12451)
- [ ] [npm/npmjs/@intlify/shared/9.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12450)

**Comment by matbmoser** [comment]
We can go for the v9.2.2 of the library. I checked the dependencies and it would work
and is also the latest stable version

**Comment by matbmoser** [comment]
Ok we will go with the v9.2.2. I will include it in our latest hotfix already to check for vulnerabilities with veracode
