### ISSUE TITLE
IP Checks for Hotfix Release v2.0.1

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#170]
## IP Checks:
There are some IP checks that were open in the upgrade from Spring Boot to v3.2.1:

## Libraries Updated:
Spring Boot `v3.1.5` -> `v3.2.1`

## Checks:
- [x] [maven/mavencentral/org.springframework.session/spring-session-jdbc/3.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12596)
- [x] [maven/mavencentral/org.springframework.data/spring-data-rest-webmvc/4.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12595)
- [x] [maven/mavencentral/org.springframework.boot/spring-boot-starter-data-rest/3.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12594)
- [x] [maven/mavencentral/org.springframework/spring-webflux/6.1.2](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12593)
- [x] [maven/mavencentral/org.apache.logging.log4j/log4j-core/2.21.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12592)
- [x] [maven/mavencentral/org.springframework.data/spring-data-rest-core/4.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12591)
- [x] [maven/mavencentral/org.springframework.boot/spring-boot-starter-reactor-netty/3.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12590)
- [x] [maven/mavencentral/org.springframework.boot/spring-boot-starter-webflux/3.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12589)
- [x] [maven/mavencentral/org.springframework.session/spring-session-core/3.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12588)
- [x] [maven/mavencentral/org.springframework.boot/spring-boot-starter-oauth2-client/3.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12587)
- [x] [maven/mavencentral/org.springframework.security/spring-security-oauth2-client/6.2.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12586)

**Comment by matbmoser** [comment]
Incredibly the Dash Bot review all the issues are approved them!

**Comment by matbmoser** [comment]
![image](https://github.com/eclipse-tractusx/digital-product-pass/assets/71728767/a61f340a-f2ee-44f1-8dfd-2056e575925c)
