### ISSUE TITLE
Quality Gate Checks (Release 3.2)

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#33]
# Introduction

We want to make public our status from the QG checks.

## QG checks
Please keep this issue open until QG X is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG X is concluded!

Product Name: Digital Product Pass
Product Owner: Thorsten Dikmann
Dev SPOC: Jochen Braun / Mathias Moser
Helm Chart Version:   
App Version:   
QG5 Approval: yes/no 

### Check of Tractus-X Release Guidelines

This QG x Check is depending on the mandatory information from our current [Release Guidelines](https://eclipse-tractusx.github.io/docs/release).

#### TRG 1 Documentation
- [x] [TRG 1.01](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) appropriate `README.md` 
- [x] [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2) appropriate `INSTALL.md` #39 
- [x] [TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) appropriate `CHANGELOG.md`
#### TRG 2 Git
- [x] [TRG 2.01](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1) default branch is named `main`
- [x] [TRG 2.03](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3) repository structure
  <details>
  <summary>Checks within TRG 2.03</summary>

  - [x] TRG 2.03 `/docs` directory contains detailed product related documentation for the Tractus-X product 
  - [x] TRG 2.03 `/charts` directory contains the Helm chart for the Tractus-X product IF available
  - [x] TRG 2.03 `AUTHORS.md` file (optional) (TRG 2.03) file 
  - [x] TRG 2.03 `CODE_OF_CONDUCT.md` file (TRG 2.03)
  - [x] TRG 2.03 `CONTRIBUTING.md` file (TRG 2.03)
  - [x] TRG 2.03 `DEPENDENCIES` file(s) with up to date content (Dash tool generated) (TRG 2.03)
  - [x] TRG 2.03 `LICENSE` file (TRG 2.03)
  - [x] TRG 2.03 `NOTICE.md` file (TRG 2.03)
  - [x] TRG 2.03 `SECURITY.md` file (TRG 2.03)
  </details>

- [x] [TRG 2.04](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4) Leading product repository
  <details>
  <summary>Checks within TRG 2.04</summary>
  
  - [x] TRG 2.04 repository name must be _productname_ without prefix or suffix
  - [x] TRG 2.04 should contain the release
  - [x] TRG 2.04 references/urls to the product's other repositories
  - [x] TRG 2.04 might contain product helm chart(s)
  - [x] TRG 2.04 README.md: contains the urls for the underlying applications
  </details>

- [x] [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5) `.tractusx` metafile in a proper format #40 
#### TRG 3 Kubernetes
- [x] [TRG 3.02](https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2) PersistentVolume and PersistentVolumeClaim is used when needed ) -> #84 
#### TRG 4 Container
- [x] [TRG 4.01](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1) [semantic versioning](https://semver.org/) and tagging 
- [x] [TRG 4.02](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2) top level `README.md` file, that contains information about the used base image  #42 
- [x] [TRG 4.03](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3) Image has `USER` command and Non Root Container #43 
  <details>
  <summary>Checks within TRG 4.03</summary>
  
  - [x] TRG 4.03 `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
  </details> #43 

- [x] #50
- [x] [TRG 4.06](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06) Notice File for `DockerHub` has all necessary information
  <details>
  <summary>Checks within TRG 4.06</summary>

  - [x] TRG 4.06 Link to the source of your base image (Container registry and GitHub if available)
  - [x] TRG 4.06 Link to your product image on `DockerHub`
  - [x] TRG 4.06 Link to your repository on `GitHub`
  - [x] TRG 4.06 Direct link to the Dockerfile used to build your image
  - [x] TRG 4.06 Link to LICENCE file in your repo as `Project License` (make clear, that this is the PROJECT licence, not an image license
  </details>

#### TRG 5 Helm
- [x] [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01) Helm chart must be released
  <details>
  <summary>Checks within TRG 5.01</summary>

  - [x] TRG 5.01 appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
  - [x] TRG 5.01 must not contain any environment specific `values-xyz.yaml` #37 
  - [x] TRG 5.01 `values.yaml` file must contain proper default values/placeholders
  - [x] TRG 5.01 No hostname provided for ingress #41 
  - [x] TRG 5.01 Ingress is disabled
  - [x] TRG 5.01 No references to any secret engine service (e.g.: Hashicorp Vault) 
  - [x] TRG 5.01 Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
  - [x] TRG 5.01 Image tag is set to the `Chart.yaml` `appVersion` property
  - [x] TRG 5.01 must be deployable to any environment without overwriting default values with a simple helm install command
  - [x] TRG 5.01 dependencies have to be declared in Chart.yaml NOT requirements.yml
  </details>
  
- [x] [TRG 5.02](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02) Helm chart location in `/charts` directory and correct structure
  <details>
  <summary>Checks within TRG 5.02</summary>
  
  - [x] TRG 5.02 each file must contain the [Apache 2.0 Licence](https://github.com/catenax-ng/foss-example/blob/main/general/LICENSE)
  - [x] TRG 5.02 latest tag is not used in helm chart be default

  ``` markdown
  charts/ 
      chartNameA/
        Chart.yaml
        ... 
      chartNameB/
        Chart.yaml
        ...
  AUTHORS.md 
  DEPENDENCIES.md 
  LICENCE 
  README.md 
  ```
  </details>

- [x] [TRG 5.04](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04)  -> CPU and Memory utilization #83
- [x] [TRG 5.06](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06) application must be configurable through the Helm chart 
- [x] [TRG 5.07](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07) dependencies are present in the `Chart.yaml` they are properly configured
- [x] [TRG 5.08](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08) a product has a single deployable helm chart that contains all components 
  <details>
  <summary>Checks within TRG 5.08</summary>

  - [x] TRG 5.08 name of the Chart should be just the product-name without prefix or suffix
  - [x] TRG 5.08 values file should contain all available variables (even from subcharts) with default values and comments about what they do
  - [x] TRG 5.08 helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values) #96
  - [x] TRG 5.08 helm test runs without errors #94 #93
  </details>
  
- [x] [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) Helm Test running properly
  <details>
  <summary>Checks within TRG 5.09</summary>

  - [x] TRG 5.09 A GitHub action exist which builds or uses the helm chart which gets released
  - [x] TRG 5.09 The GitHub action can be triggered manually through Github WebUI manually running a workflow
  - [x] TRG 5.09 Helm test verifies that the application is up and running #93
  </details>
- [x] [TRG 5.10](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10) Products need to support 3 versions at a time #96 (We tested for 4 versions)
  <details>
  <summary>Checks within TRG 5.10</summary> 

  - [x] TRG 5.10 latest (K8s version 1.25)
  - [x] TRG 5.10 latest - 1 (K8s version 1.24)
  - [x] TRG 5.10 latest - 2  (K8s version 1.23)
  </details>
- [x] [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11) Upgradeability PRERELEASE #90 
  <details>
  <summary>Checks within TRG 5.11</summary>

  - [x] TRG 5.11 Based on the Helm test workflow, you must provide a GitHub action which takes the latest released helm chart, does an installation of it and then execute the upgrade to the current / new version.
  </details>
  
#### TRG 6 Released Helm Chart 
- [x] [TRG 6.01](https://eclipse-tractusx.github.io/docs/release/trg-6/trg-6-1) Released Helm Chart 
#### TRG 7 Open Source Governance
- [x] [TRG 7.01](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01) Legal Documentation
- [x] [TRG 7.02](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) License and copyright header  
- [x] [TRG 7.03] IP checks for project content #95
- [x] [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) IP checks for 3rd party content -> Done using Dash Tool
  <details>
  <summary>Checks within TRG 7.04</summary>

  - [x] TRG 7.04 DEPENDENCIES file is up-to-date and reflects the current use of the 3rd party content
  - [x] TRG 7.04 all libraries listed there should have the status "approved"
  - [x] TRG 7.04 no libraries with status "rejected"
  - [x] TRG 7.04 for libraries with status "restricted", the according IP issues must be present (issue number in the source column)
  </details>
- [x] [TRG 7.05](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05) Legal information for distributions [Included in [v1.0.0-alpha](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v1.0.0-alpha)]
- [x] [TRG 7.06](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06) Legal information for end user content [Included in [v1.0.0-alpha](https://github.com/eclipse-tractusx/digital-product-pass/releases/tag/v1.0.0-alpha)]
- [x] [TRG 7.07](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07) Legal notice for documentation #60 -> Won't do because there was no clarification about which documentation needs to be CC-BY and what needs to be Apache-2.0 (Everything has the Apache Version)

**Comment by matbmoser** [comment]
TRG Requirements for QG4 Approved by @SebastianBezold https://github.com/eclipse-tractusx/digital-product-pass/issues/108
